FROM python:3.9-slim-bullseye as opcut-base
WORKDIR /opcut
RUN apt update -qy && \
    apt install -qy pkg-config gcc libcairo2-dev

FROM opcut-base as opcut-build
WORKDIR /opcut
COPY . .
RUN apt install -qy nodejs yarnpkg && \
    ln -sT /usr/bin/yarnpkg /usr/bin/yarn && \
    pip install -qq -r requirements.pip.dev.txt && \
    doit

FROM opcut-base as opcut-run
WORKDIR /opcut
COPY --from=opcut-build /opcut/build/dist/*.whl .
RUN pip install -qq *.whl && \
    rm *.whl
