---
"$schema": "http://json-schema.org/schema#"
id: "opcut://logging.yaml#"
title: Logging
description: Logging configuration
type: object
required:
    - version
properties:
    version:
        title: Version
        type: integer
        default: 1
    formatters:
        title: Formatters
        type: object
        patternProperties:
            "(.)+":
                title: Formatter
                type: object
                properties:
                    format:
                        title: Format
                        type: string
                        default: null
                    datefmt:
                        title: Date format
                        type: string
                        default: null
    filters:
        title: Filters
        type: object
        patternProperties:
            "(.)+":
                title: Filter
                type: object
                properties:
                    name:
                        title: Logger name
                        type: string
                        default: ''
    handlers:
        title: Handlers
        type: object
        patternProperties:
            "(.)+":
                title: Handler
                type: object
                description: |
                    Additional properties are passed as keyword arguments to
                    constructor
                required:
                    - class
                properties:
                    class:
                        title: Class
                        type: string
                    level:
                        title: Level
                        type: string
                    formatter:
                        title: Formatter
                        type: string
                    filters:
                        title: Filters
                        type: array
                        items:
                            title: Filter id
                            type: string
    loggers:
        title: Loggers
        type: object
        patternProperties:
            "(.)+":
                title: Logger
                type: object
                properties:
                    level:
                        title: Level
                        type: string
                    propagate:
                        title: Propagate
                        type: boolean
                    filters:
                        title: Filters
                        type: array
                        items:
                            title: Filter id
                            type: string
                    handlers:
                        title: Handlers
                        type: array
                        items:
                            title: Handler id
                            type: string
    root:
        title: Root logger
        type: object
        properties:
            level:
                title: Level
                type: string
            filters:
                title: Filters
                type: array
                items:
                    title: Filter id
                    type: string
            handlers:
                title: Handlers
                type: array
                items:
                    title: Handler id
                    type: string
    incremental:
        title: Incremental configuration
        type: boolean
        default: false
    disable_existing_loggers:
        title: Disable existing loggers
        type: boolean
        default: true
...
